QT += gui
QT += widgets
QT += concurrent
QT += network

TEMPLATE = lib
CONFIG += staticlib

CONFIG += c++20

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

INCLUDEPATH += libs/range-v3/include
INCLUDEPATH += libs/nlohmann-json/single_include

HEADERS += \
    Avoidance/path_checker.h \
    Avoidance/path_finder.h \
    Avoidance/path_planner.h \
    Avoidance/pathstep.h \
    Communications/messagePublisher.h \
    Communications/subscriber.h \
    Detection/detectionmanager.h \
    Detection/detectionutilities.h \
    Detection/sensor.h \
    JSON_overlay/jsonstatemachine.h \
    Scenes/playground.h \
    Scenes/robot.h \
    Strategy/Actions/actionfactory.h \
    Strategy/GOAP/action.hpp \
    Strategy/GOAP/goal.hpp \
    Strategy/GOAP/goap.hpp \
    Strategy/GOAP/planner.hpp \
    Strategy/GOAP/world_state.hpp \
    Strategy/STM/event.h \
    Strategy/STM/state.h \
    Strategy/STM/stm.h \
    Strategy/STM/transition.h \
    Scenes/obstacle.h \
    Scenes/gameelement.h \
    Strategy/strategymanager.h \
    Utils/Singleton.h \
    gamestate.h \
    libs/nlohmann-json/include/nlohmann/adl_serializer.hpp \
    libs/nlohmann-json/include/nlohmann/byte_container_with_subtype.hpp \
    libs/nlohmann-json/include/nlohmann/detail/abi_macros.hpp \
    libs/nlohmann-json/include/nlohmann/detail/conversions/from_json.hpp \
    libs/nlohmann-json/include/nlohmann/detail/conversions/to_chars.hpp \
    libs/nlohmann-json/include/nlohmann/detail/conversions/to_json.hpp \
    libs/nlohmann-json/include/nlohmann/detail/exceptions.hpp \
    libs/nlohmann-json/include/nlohmann/detail/hash.hpp \
    libs/nlohmann-json/include/nlohmann/detail/input/binary_reader.hpp \
    libs/nlohmann-json/include/nlohmann/detail/input/input_adapters.hpp \
    libs/nlohmann-json/include/nlohmann/detail/input/json_sax.hpp \
    libs/nlohmann-json/include/nlohmann/detail/input/lexer.hpp \
    libs/nlohmann-json/include/nlohmann/detail/input/parser.hpp \
    libs/nlohmann-json/include/nlohmann/detail/input/position_t.hpp \
    libs/nlohmann-json/include/nlohmann/detail/iterators/internal_iterator.hpp \
    libs/nlohmann-json/include/nlohmann/detail/iterators/iter_impl.hpp \
    libs/nlohmann-json/include/nlohmann/detail/iterators/iteration_proxy.hpp \
    libs/nlohmann-json/include/nlohmann/detail/iterators/iterator_traits.hpp \
    libs/nlohmann-json/include/nlohmann/detail/iterators/json_reverse_iterator.hpp \
    libs/nlohmann-json/include/nlohmann/detail/iterators/primitive_iterator.hpp \
    libs/nlohmann-json/include/nlohmann/detail/json_custom_base_class.hpp \
    libs/nlohmann-json/include/nlohmann/detail/json_pointer.hpp \
    libs/nlohmann-json/include/nlohmann/detail/json_ref.hpp \
    libs/nlohmann-json/include/nlohmann/detail/macro_scope.hpp \
    libs/nlohmann-json/include/nlohmann/detail/macro_unscope.hpp \
    libs/nlohmann-json/include/nlohmann/detail/meta/call_std/begin.hpp \
    libs/nlohmann-json/include/nlohmann/detail/meta/call_std/end.hpp \
    libs/nlohmann-json/include/nlohmann/detail/meta/cpp_future.hpp \
    libs/nlohmann-json/include/nlohmann/detail/meta/detected.hpp \
    libs/nlohmann-json/include/nlohmann/detail/meta/identity_tag.hpp \
    libs/nlohmann-json/include/nlohmann/detail/meta/is_sax.hpp \
    libs/nlohmann-json/include/nlohmann/detail/meta/std_fs.hpp \
    libs/nlohmann-json/include/nlohmann/detail/meta/type_traits.hpp \
    libs/nlohmann-json/include/nlohmann/detail/meta/void_t.hpp \
    libs/nlohmann-json/include/nlohmann/detail/output/binary_writer.hpp \
    libs/nlohmann-json/include/nlohmann/detail/output/output_adapters.hpp \
    libs/nlohmann-json/include/nlohmann/detail/output/serializer.hpp \
    libs/nlohmann-json/include/nlohmann/detail/string_concat.hpp \
    libs/nlohmann-json/include/nlohmann/detail/string_escape.hpp \
    libs/nlohmann-json/include/nlohmann/detail/value_t.hpp \
    libs/nlohmann-json/include/nlohmann/json.hpp \
    libs/nlohmann-json/include/nlohmann/json_fwd.hpp \
    libs/nlohmann-json/include/nlohmann/ordered_map.hpp \
    libs/nlohmann-json/include/nlohmann/thirdparty/hedley/hedley.hpp \
    libs/nlohmann-json/include/nlohmann/thirdparty/hedley/hedley_undef.hpp \
    libs/nlohmann-json/single_include/nlohmann/json.hpp \
    libs/nlohmann-json/single_include/nlohmann/json_fwd.hpp \
    libs/range-v3/include/concepts/compare.hpp \
    libs/range-v3/include/concepts/concepts.hpp \
    libs/range-v3/include/concepts/swap.hpp \
    libs/range-v3/include/concepts/type_traits.hpp \
    libs/range-v3/include/meta/meta.hpp \
    libs/range-v3/include/meta/meta_fwd.hpp \
    libs/range-v3/include/range/v3/action.hpp \
    libs/range-v3/include/range/v3/action/action.hpp \
    libs/range-v3/include/range/v3/action/adjacent_remove_if.hpp \
    libs/range-v3/include/range/v3/action/concepts.hpp \
    libs/range-v3/include/range/v3/action/drop.hpp \
    libs/range-v3/include/range/v3/action/drop_while.hpp \
    libs/range-v3/include/range/v3/action/erase.hpp \
    libs/range-v3/include/range/v3/action/insert.hpp \
    libs/range-v3/include/range/v3/action/join.hpp \
    libs/range-v3/include/range/v3/action/push_back.hpp \
    libs/range-v3/include/range/v3/action/push_front.hpp \
    libs/range-v3/include/range/v3/action/remove.hpp \
    libs/range-v3/include/range/v3/action/remove_if.hpp \
    libs/range-v3/include/range/v3/action/reverse.hpp \
    libs/range-v3/include/range/v3/action/shuffle.hpp \
    libs/range-v3/include/range/v3/action/slice.hpp \
    libs/range-v3/include/range/v3/action/sort.hpp \
    libs/range-v3/include/range/v3/action/split.hpp \
    libs/range-v3/include/range/v3/action/split_when.hpp \
    libs/range-v3/include/range/v3/action/stable_sort.hpp \
    libs/range-v3/include/range/v3/action/stride.hpp \
    libs/range-v3/include/range/v3/action/take.hpp \
    libs/range-v3/include/range/v3/action/take_while.hpp \
    libs/range-v3/include/range/v3/action/transform.hpp \
    libs/range-v3/include/range/v3/action/unique.hpp \
    libs/range-v3/include/range/v3/action/unstable_remove_if.hpp \
    libs/range-v3/include/range/v3/algorithm.hpp \
    libs/range-v3/include/range/v3/algorithm/adjacent_find.hpp \
    libs/range-v3/include/range/v3/algorithm/adjacent_remove_if.hpp \
    libs/range-v3/include/range/v3/algorithm/all_of.hpp \
    libs/range-v3/include/range/v3/algorithm/any_of.hpp \
    libs/range-v3/include/range/v3/algorithm/aux_/equal_range_n.hpp \
    libs/range-v3/include/range/v3/algorithm/aux_/lower_bound_n.hpp \
    libs/range-v3/include/range/v3/algorithm/aux_/merge_n.hpp \
    libs/range-v3/include/range/v3/algorithm/aux_/merge_n_with_buffer.hpp \
    libs/range-v3/include/range/v3/algorithm/aux_/partition_point_n.hpp \
    libs/range-v3/include/range/v3/algorithm/aux_/sort_n_with_buffer.hpp \
    libs/range-v3/include/range/v3/algorithm/aux_/upper_bound_n.hpp \
    libs/range-v3/include/range/v3/algorithm/binary_search.hpp \
    libs/range-v3/include/range/v3/algorithm/contains.hpp \
    libs/range-v3/include/range/v3/algorithm/contains_subrange.hpp \
    libs/range-v3/include/range/v3/algorithm/copy.hpp \
    libs/range-v3/include/range/v3/algorithm/copy_backward.hpp \
    libs/range-v3/include/range/v3/algorithm/copy_if.hpp \
    libs/range-v3/include/range/v3/algorithm/copy_n.hpp \
    libs/range-v3/include/range/v3/algorithm/count.hpp \
    libs/range-v3/include/range/v3/algorithm/count_if.hpp \
    libs/range-v3/include/range/v3/algorithm/ends_with.hpp \
    libs/range-v3/include/range/v3/algorithm/equal.hpp \
    libs/range-v3/include/range/v3/algorithm/equal_range.hpp \
    libs/range-v3/include/range/v3/algorithm/fill.hpp \
    libs/range-v3/include/range/v3/algorithm/fill_n.hpp \
    libs/range-v3/include/range/v3/algorithm/find.hpp \
    libs/range-v3/include/range/v3/algorithm/find_end.hpp \
    libs/range-v3/include/range/v3/algorithm/find_first_of.hpp \
    libs/range-v3/include/range/v3/algorithm/find_if.hpp \
    libs/range-v3/include/range/v3/algorithm/find_if_not.hpp \
    libs/range-v3/include/range/v3/algorithm/fold.hpp \
    libs/range-v3/include/range/v3/algorithm/fold_left.hpp \
    libs/range-v3/include/range/v3/algorithm/fold_right.hpp \
    libs/range-v3/include/range/v3/algorithm/for_each.hpp \
    libs/range-v3/include/range/v3/algorithm/for_each_n.hpp \
    libs/range-v3/include/range/v3/algorithm/generate.hpp \
    libs/range-v3/include/range/v3/algorithm/generate_n.hpp \
    libs/range-v3/include/range/v3/algorithm/heap_algorithm.hpp \
    libs/range-v3/include/range/v3/algorithm/inplace_merge.hpp \
    libs/range-v3/include/range/v3/algorithm/is_partitioned.hpp \
    libs/range-v3/include/range/v3/algorithm/is_sorted.hpp \
    libs/range-v3/include/range/v3/algorithm/is_sorted_until.hpp \
    libs/range-v3/include/range/v3/algorithm/lexicographical_compare.hpp \
    libs/range-v3/include/range/v3/algorithm/lower_bound.hpp \
    libs/range-v3/include/range/v3/algorithm/max.hpp \
    libs/range-v3/include/range/v3/algorithm/max_element.hpp \
    libs/range-v3/include/range/v3/algorithm/merge.hpp \
    libs/range-v3/include/range/v3/algorithm/min.hpp \
    libs/range-v3/include/range/v3/algorithm/min_element.hpp \
    libs/range-v3/include/range/v3/algorithm/minmax.hpp \
    libs/range-v3/include/range/v3/algorithm/minmax_element.hpp \
    libs/range-v3/include/range/v3/algorithm/mismatch.hpp \
    libs/range-v3/include/range/v3/algorithm/move.hpp \
    libs/range-v3/include/range/v3/algorithm/move_backward.hpp \
    libs/range-v3/include/range/v3/algorithm/none_of.hpp \
    libs/range-v3/include/range/v3/algorithm/nth_element.hpp \
    libs/range-v3/include/range/v3/algorithm/partial_sort.hpp \
    libs/range-v3/include/range/v3/algorithm/partial_sort_copy.hpp \
    libs/range-v3/include/range/v3/algorithm/partition.hpp \
    libs/range-v3/include/range/v3/algorithm/partition_copy.hpp \
    libs/range-v3/include/range/v3/algorithm/partition_point.hpp \
    libs/range-v3/include/range/v3/algorithm/permutation.hpp \
    libs/range-v3/include/range/v3/algorithm/remove.hpp \
    libs/range-v3/include/range/v3/algorithm/remove_copy.hpp \
    libs/range-v3/include/range/v3/algorithm/remove_copy_if.hpp \
    libs/range-v3/include/range/v3/algorithm/remove_if.hpp \
    libs/range-v3/include/range/v3/algorithm/replace.hpp \
    libs/range-v3/include/range/v3/algorithm/replace_copy.hpp \
    libs/range-v3/include/range/v3/algorithm/replace_copy_if.hpp \
    libs/range-v3/include/range/v3/algorithm/replace_if.hpp \
    libs/range-v3/include/range/v3/algorithm/result_types.hpp \
    libs/range-v3/include/range/v3/algorithm/reverse.hpp \
    libs/range-v3/include/range/v3/algorithm/reverse_copy.hpp \
    libs/range-v3/include/range/v3/algorithm/rotate.hpp \
    libs/range-v3/include/range/v3/algorithm/rotate_copy.hpp \
    libs/range-v3/include/range/v3/algorithm/sample.hpp \
    libs/range-v3/include/range/v3/algorithm/search.hpp \
    libs/range-v3/include/range/v3/algorithm/search_n.hpp \
    libs/range-v3/include/range/v3/algorithm/set_algorithm.hpp \
    libs/range-v3/include/range/v3/algorithm/shuffle.hpp \
    libs/range-v3/include/range/v3/algorithm/sort.hpp \
    libs/range-v3/include/range/v3/algorithm/stable_partition.hpp \
    libs/range-v3/include/range/v3/algorithm/stable_sort.hpp \
    libs/range-v3/include/range/v3/algorithm/starts_with.hpp \
    libs/range-v3/include/range/v3/algorithm/swap_ranges.hpp \
    libs/range-v3/include/range/v3/algorithm/tagspec.hpp \
    libs/range-v3/include/range/v3/algorithm/transform.hpp \
    libs/range-v3/include/range/v3/algorithm/unique.hpp \
    libs/range-v3/include/range/v3/algorithm/unique_copy.hpp \
    libs/range-v3/include/range/v3/algorithm/unstable_remove_if.hpp \
    libs/range-v3/include/range/v3/algorithm/upper_bound.hpp \
    libs/range-v3/include/range/v3/all.hpp \
    libs/range-v3/include/range/v3/at.hpp \
    libs/range-v3/include/range/v3/back.hpp \
    libs/range-v3/include/range/v3/begin_end.hpp \
    libs/range-v3/include/range/v3/compare.hpp \
    libs/range-v3/include/range/v3/core.hpp \
    libs/range-v3/include/range/v3/data.hpp \
    libs/range-v3/include/range/v3/detail/adl_get.hpp \
    libs/range-v3/include/range/v3/detail/config.hpp \
    libs/range-v3/include/range/v3/detail/epilogue.hpp \
    libs/range-v3/include/range/v3/detail/prologue.hpp \
    libs/range-v3/include/range/v3/detail/range_access.hpp \
    libs/range-v3/include/range/v3/detail/satisfy_boost_range.hpp \
    libs/range-v3/include/range/v3/detail/variant.hpp \
    libs/range-v3/include/range/v3/detail/with_braced_init_args.hpp \
    libs/range-v3/include/range/v3/distance.hpp \
    libs/range-v3/include/range/v3/empty.hpp \
    libs/range-v3/include/range/v3/experimental/utility/generator.hpp \
    libs/range-v3/include/range/v3/experimental/view/shared.hpp \
    libs/range-v3/include/range/v3/front.hpp \
    libs/range-v3/include/range/v3/functional.hpp \
    libs/range-v3/include/range/v3/functional/arithmetic.hpp \
    libs/range-v3/include/range/v3/functional/bind.hpp \
    libs/range-v3/include/range/v3/functional/bind_back.hpp \
    libs/range-v3/include/range/v3/functional/comparisons.hpp \
    libs/range-v3/include/range/v3/functional/compose.hpp \
    libs/range-v3/include/range/v3/functional/concepts.hpp \
    libs/range-v3/include/range/v3/functional/identity.hpp \
    libs/range-v3/include/range/v3/functional/indirect.hpp \
    libs/range-v3/include/range/v3/functional/invoke.hpp \
    libs/range-v3/include/range/v3/functional/not_fn.hpp \
    libs/range-v3/include/range/v3/functional/on.hpp \
    libs/range-v3/include/range/v3/functional/overload.hpp \
    libs/range-v3/include/range/v3/functional/pipeable.hpp \
    libs/range-v3/include/range/v3/functional/reference_wrapper.hpp \
    libs/range-v3/include/range/v3/getlines.hpp \
    libs/range-v3/include/range/v3/index.hpp \
    libs/range-v3/include/range/v3/istream_range.hpp \
    libs/range-v3/include/range/v3/iterator.hpp \
    libs/range-v3/include/range/v3/iterator/access.hpp \
    libs/range-v3/include/range/v3/iterator/basic_iterator.hpp \
    libs/range-v3/include/range/v3/iterator/common_iterator.hpp \
    libs/range-v3/include/range/v3/iterator/concepts.hpp \
    libs/range-v3/include/range/v3/iterator/counted_iterator.hpp \
    libs/range-v3/include/range/v3/iterator/default_sentinel.hpp \
    libs/range-v3/include/range/v3/iterator/diffmax_t.hpp \
    libs/range-v3/include/range/v3/iterator/insert_iterators.hpp \
    libs/range-v3/include/range/v3/iterator/move_iterators.hpp \
    libs/range-v3/include/range/v3/iterator/operations.hpp \
    libs/range-v3/include/range/v3/iterator/reverse_iterator.hpp \
    libs/range-v3/include/range/v3/iterator/stream_iterators.hpp \
    libs/range-v3/include/range/v3/iterator/traits.hpp \
    libs/range-v3/include/range/v3/iterator/unreachable_sentinel.hpp \
    libs/range-v3/include/range/v3/iterator_range.hpp \
    libs/range-v3/include/range/v3/numeric.hpp \
    libs/range-v3/include/range/v3/numeric/accumulate.hpp \
    libs/range-v3/include/range/v3/numeric/adjacent_difference.hpp \
    libs/range-v3/include/range/v3/numeric/inner_product.hpp \
    libs/range-v3/include/range/v3/numeric/iota.hpp \
    libs/range-v3/include/range/v3/numeric/partial_sum.hpp \
    libs/range-v3/include/range/v3/range.hpp \
    libs/range-v3/include/range/v3/range/access.hpp \
    libs/range-v3/include/range/v3/range/concepts.hpp \
    libs/range-v3/include/range/v3/range/conversion.hpp \
    libs/range-v3/include/range/v3/range/dangling.hpp \
    libs/range-v3/include/range/v3/range/operations.hpp \
    libs/range-v3/include/range/v3/range/primitives.hpp \
    libs/range-v3/include/range/v3/range/traits.hpp \
    libs/range-v3/include/range/v3/range_access.hpp \
    libs/range-v3/include/range/v3/range_concepts.hpp \
    libs/range-v3/include/range/v3/range_for.hpp \
    libs/range-v3/include/range/v3/range_fwd.hpp \
    libs/range-v3/include/range/v3/range_traits.hpp \
    libs/range-v3/include/range/v3/size.hpp \
    libs/range-v3/include/range/v3/span.hpp \
    libs/range-v3/include/range/v3/to_container.hpp \
    libs/range-v3/include/range/v3/utility.hpp \
    libs/range-v3/include/range/v3/utility/addressof.hpp \
    libs/range-v3/include/range/v3/utility/any.hpp \
    libs/range-v3/include/range/v3/utility/associated_types.hpp \
    libs/range-v3/include/range/v3/utility/basic_iterator.hpp \
    libs/range-v3/include/range/v3/utility/box.hpp \
    libs/range-v3/include/range/v3/utility/common_iterator.hpp \
    libs/range-v3/include/range/v3/utility/common_tuple.hpp \
    libs/range-v3/include/range/v3/utility/common_type.hpp \
    libs/range-v3/include/range/v3/utility/compressed_pair.hpp \
    libs/range-v3/include/range/v3/utility/concepts.hpp \
    libs/range-v3/include/range/v3/utility/copy.hpp \
    libs/range-v3/include/range/v3/utility/counted_iterator.hpp \
    libs/range-v3/include/range/v3/utility/dangling.hpp \
    libs/range-v3/include/range/v3/utility/functional.hpp \
    libs/range-v3/include/range/v3/utility/get.hpp \
    libs/range-v3/include/range/v3/utility/in_place.hpp \
    libs/range-v3/include/range/v3/utility/infinity.hpp \
    libs/range-v3/include/range/v3/utility/invoke.hpp \
    libs/range-v3/include/range/v3/utility/iterator.hpp \
    libs/range-v3/include/range/v3/utility/iterator_concepts.hpp \
    libs/range-v3/include/range/v3/utility/iterator_traits.hpp \
    libs/range-v3/include/range/v3/utility/memory.hpp \
    libs/range-v3/include/range/v3/utility/move.hpp \
    libs/range-v3/include/range/v3/utility/nullptr_v.hpp \
    libs/range-v3/include/range/v3/utility/optional.hpp \
    libs/range-v3/include/range/v3/utility/polymorphic_cast.hpp \
    libs/range-v3/include/range/v3/utility/random.hpp \
    libs/range-v3/include/range/v3/utility/scope_exit.hpp \
    libs/range-v3/include/range/v3/utility/semiregular.hpp \
    libs/range-v3/include/range/v3/utility/semiregular_box.hpp \
    libs/range-v3/include/range/v3/utility/static_const.hpp \
    libs/range-v3/include/range/v3/utility/swap.hpp \
    libs/range-v3/include/range/v3/utility/tagged_pair.hpp \
    libs/range-v3/include/range/v3/utility/tagged_tuple.hpp \
    libs/range-v3/include/range/v3/utility/tuple_algorithm.hpp \
    libs/range-v3/include/range/v3/utility/unreachable.hpp \
    libs/range-v3/include/range/v3/utility/variant.hpp \
    libs/range-v3/include/range/v3/version.hpp \
    libs/range-v3/include/range/v3/view.hpp \
    libs/range-v3/include/range/v3/view/adaptor.hpp \
    libs/range-v3/include/range/v3/view/addressof.hpp \
    libs/range-v3/include/range/v3/view/adjacent_filter.hpp \
    libs/range-v3/include/range/v3/view/adjacent_remove_if.hpp \
    libs/range-v3/include/range/v3/view/all.hpp \
    libs/range-v3/include/range/v3/view/any_view.hpp \
    libs/range-v3/include/range/v3/view/bounded.hpp \
    libs/range-v3/include/range/v3/view/c_str.hpp \
    libs/range-v3/include/range/v3/view/cache1.hpp \
    libs/range-v3/include/range/v3/view/cartesian_product.hpp \
    libs/range-v3/include/range/v3/view/chunk.hpp \
    libs/range-v3/include/range/v3/view/chunk_by.hpp \
    libs/range-v3/include/range/v3/view/common.hpp \
    libs/range-v3/include/range/v3/view/concat.hpp \
    libs/range-v3/include/range/v3/view/const.hpp \
    libs/range-v3/include/range/v3/view/counted.hpp \
    libs/range-v3/include/range/v3/view/cycle.hpp \
    libs/range-v3/include/range/v3/view/delimit.hpp \
    libs/range-v3/include/range/v3/view/drop.hpp \
    libs/range-v3/include/range/v3/view/drop_exactly.hpp \
    libs/range-v3/include/range/v3/view/drop_last.hpp \
    libs/range-v3/include/range/v3/view/drop_while.hpp \
    libs/range-v3/include/range/v3/view/empty.hpp \
    libs/range-v3/include/range/v3/view/enumerate.hpp \
    libs/range-v3/include/range/v3/view/exclusive_scan.hpp \
    libs/range-v3/include/range/v3/view/facade.hpp \
    libs/range-v3/include/range/v3/view/filter.hpp \
    libs/range-v3/include/range/v3/view/for_each.hpp \
    libs/range-v3/include/range/v3/view/generate.hpp \
    libs/range-v3/include/range/v3/view/generate_n.hpp \
    libs/range-v3/include/range/v3/view/getlines.hpp \
    libs/range-v3/include/range/v3/view/group_by.hpp \
    libs/range-v3/include/range/v3/view/indices.hpp \
    libs/range-v3/include/range/v3/view/indirect.hpp \
    libs/range-v3/include/range/v3/view/interface.hpp \
    libs/range-v3/include/range/v3/view/intersperse.hpp \
    libs/range-v3/include/range/v3/view/iota.hpp \
    libs/range-v3/include/range/v3/view/istream.hpp \
    libs/range-v3/include/range/v3/view/join.hpp \
    libs/range-v3/include/range/v3/view/linear_distribute.hpp \
    libs/range-v3/include/range/v3/view/map.hpp \
    libs/range-v3/include/range/v3/view/move.hpp \
    libs/range-v3/include/range/v3/view/partial_sum.hpp \
    libs/range-v3/include/range/v3/view/ref.hpp \
    libs/range-v3/include/range/v3/view/remove.hpp \
    libs/range-v3/include/range/v3/view/remove_if.hpp \
    libs/range-v3/include/range/v3/view/repeat.hpp \
    libs/range-v3/include/range/v3/view/repeat_n.hpp \
    libs/range-v3/include/range/v3/view/replace.hpp \
    libs/range-v3/include/range/v3/view/replace_if.hpp \
    libs/range-v3/include/range/v3/view/reverse.hpp \
    libs/range-v3/include/range/v3/view/sample.hpp \
    libs/range-v3/include/range/v3/view/set_algorithm.hpp \
    libs/range-v3/include/range/v3/view/single.hpp \
    libs/range-v3/include/range/v3/view/slice.hpp \
    libs/range-v3/include/range/v3/view/sliding.hpp \
    libs/range-v3/include/range/v3/view/span.hpp \
    libs/range-v3/include/range/v3/view/split.hpp \
    libs/range-v3/include/range/v3/view/split_when.hpp \
    libs/range-v3/include/range/v3/view/stride.hpp \
    libs/range-v3/include/range/v3/view/subrange.hpp \
    libs/range-v3/include/range/v3/view/tail.hpp \
    libs/range-v3/include/range/v3/view/take.hpp \
    libs/range-v3/include/range/v3/view/take_exactly.hpp \
    libs/range-v3/include/range/v3/view/take_last.hpp \
    libs/range-v3/include/range/v3/view/take_while.hpp \
    libs/range-v3/include/range/v3/view/tokenize.hpp \
    libs/range-v3/include/range/v3/view/transform.hpp \
    libs/range-v3/include/range/v3/view/trim.hpp \
    libs/range-v3/include/range/v3/view/unbounded.hpp \
    libs/range-v3/include/range/v3/view/unique.hpp \
    libs/range-v3/include/range/v3/view/view.hpp \
    libs/range-v3/include/range/v3/view/zip.hpp \
    libs/range-v3/include/range/v3/view/zip_with.hpp \
    libs/range-v3/include/range/v3/view_adaptor.hpp \
    libs/range-v3/include/range/v3/view_facade.hpp \
    libs/range-v3/include/range/v3/view_interface.hpp \
    libs/range-v3/include/std/detail/associated_types.hpp \
    libs/range-v3/include/std/iterator

QMAKE_CXXFLAGS += -Werror

# Default rules for deployment.
unix {
    target.path = $$[QT_INSTALL_PLUGINS]/generic
}
!isEmpty(target.path): INSTALLS += target
